apiVersion: v1
kind: Pod
metadata:
  name: cvmfs-server
spec:
  containers:
    - name: cvmfs-server
      image: localhost/cvmfs-server:latest
      imagePullPolicy: Never
      ports:
        - name: http
          containerPort: 80
          hostPort: 8080
      securityContext:
        capabilities:
          add:
            - SYS_ADMIN
      resources:
        requests:
          cpu: 125m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
      volumeMounts:
        - name: cvmfs-state
          mountPath: /var/spool/cvmfs
          readOnly: false
        - name: srv-cvmfs
          mountPath: /srv/cvmfs
          readOnly: false
        - name: sion-csquare-run-keys
          mountPath: /etc/cvmfs/keys/sion.csquare.run
          readOnly: true
        - name: cvmfs-server-local
          mountPath: /etc/cvmfs/server.local
          readOnly: true
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: cvmfs-setup-env
          mountPath: /etc/cvmfs-setup/env
          readOnly: true
  volumes:
    - name: srv-cvmfs
      hostPath:
        path: ./volumes/srv-cvmfs
    - name: cvmfs-state
      hostPath:
        path: ./volumes/cvmfs-state
    - name: sion-csquare-run-keys
      hostPath:
        path: ./secrets/sion.csquare.run
        type: Directory
    - name: cvmfs-server-local
      hostPath:
        path: ./config/cvmfs/server.local
        type: File
    - name: cvmfs-setup-env
      hostPath:
        path: ./config/cvmfs-setup/env
        type: File
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
